# -*- coding: utf-8 -*-
{
    'name': "OdooCMS Student Portal",
    'summary': """Student Web Portal""",
    'description': """Web Portal for Students""",
    'author': "IDT",
    'company': 'IDT',
    'website': 'http://www.infinitedt.com',
    'category': 'OdooCMS',
    'version': '13.0.0.0',
    'sequence': '1',
    'application': 'true',
    'depends': ['website','odoocms','cms_notifications','cms_surveys','odoocms_assets'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/layout/studentportal_layout.xml',
        'views/profile/studentProfile.xml',
        'views/notification/student_notifications.xml',
        'views/invoice/invoices.xml',
        'views/attendance/attendance.xml',
        'views/errorpage/errorpage.xml',
        'views/enrollment/student_enrollments.xml',
        'views/requests/requests.xml',
        'views/result/student_results.xml',
        'views/timetable/student_time_table.xml',
        'views/survey/surveys.xml',
        'views/dashboard/student_dashboard.xml',
        'views/hostel/hostels.xml',
        'views/password/student_password_reset.xml',
    ],
}
