from . import odoocms_hostel_data_import
from . import odoocms_student_hostel_shift_wiz
from . import odoocms_hostel_rooms_deallocation_wiz
from . import reassignment_students_import_wiz
from . import odoocms_room_generate_wiz
from . import odoocms_hostel_room_mapping_wiz
from . import odoocms_student_room_assignment_wiz
from . import odoocms_student_room_vacant_wiz
from . import odoocms_student_hostel_data_import
from . import odoocms_hostel_room_bulk_vacant
from . import odoocms_faculty_hostel_shift_wiz
from . import odoocms_faculty_room_assignment_wiz
from . import odoocms_faculty_room_vacant_wiz